name: Deploy images

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - blueprint: fedora-imagebuilder
            container_tag: fedora-latest
          - blueprint: centos-minimal
            container_tag: centos-stream9
    steps:
      - name: Checkout repo
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Fill in the AWS template
        run: |
          cat shared/aws-template.toml | envsubst > shared/aws-config.toml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: majors-vmimport-bucket
          AWS_DEFAULT_REGION: us-east-1
          IMAGE_KEY: "${{ matrix.blueprint }}-${{ github.run_id }}"

      - name: Run the build
        run: ./build-image.sh
        env:
          BLUEPRINT_NAME: ${{ matrix.blueprint }}
          IMAGE_KEY: "${{ matrix.blueprint }}-${{ github.run_id }}"
          CONTAINER: "ghcr.io/major/imagebuilder/${{ matrix.container_tag }}:main"
