name: Build images

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - blueprint: installer
            container_tag: fedora-rawhide
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run the build
        run: ./build-image.sh
        env:
          BLUEPRINT_NAME: ${{ matrix.blueprint }}
          CONTAINER: "ghcr.io/ondrejbudai/osbuild-composer-container:${{ matrix.container_tag }}"
